\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename README.info
@settitle Wallabag.el
@documentencoding UTF-8
@documentlanguage en
@c %**end of header

@dircategory Emacs
@direntry
* Wallabag.el: (wallabag.el).
@end direntry

@finalout
@titlepage
@title Wallabag.el
@author Ian FitzPatrick
@end titlepage

@contents

@ifnottex
@node Top
@top Wallabag.el

@uref{https://wallabag.org/, Wallabag} is a self-hostable bookmark manager that provides RSS feeds of your
bookmarks. With Wallabag.el you can quickly send urls to wallabag.

@strong{Disclaimer:} wallabag.el is currently in alpha
@end ifnottex

@menu
* Contents::
* Features::
* Screenshots::
* Installation::
* Usage::
* Changelog::
* Notes::
* License::

@detailmenu
--- The Detailed Node Listing ---

Installation

* Prerequisites::
* Dependencies::
* Quelpa::

Usage

* Commands::

Changelog

* 0.0.2-alpha: 002-alpha. 
* 0.0.1-alpha: 001-alpha. 

Notes

* Known issues::
* Credits::

@end detailmenu
@end menu

@node Contents
@chapter Contents

@itemize
@item
@item
@item
@item
@item
@item
@end itemize

@node Features
@chapter Features

@itemize
@item
Easily add links from @uref{https://github.com/skeeto/elfeed, elfeed}, eww, or whatever is at point to @uref{https://wallabag.org/, wallabag}
@item
Easily archive (mark as read) or delete articles, when browsing a wallabag feed in elfeed.
@end itemize

@emph{Planned features & improvements:}

@itemize
@item
Article tagging (aligned with elfeed)
@item
Better sync between elfeed & wallabag
@end itemize

@node Screenshots
@chapter Screenshots

Coming soon

@image{images/wallabag-demo,,,,gif}

@node Installation
@chapter Installation

@menu
* Prerequisites::
* Dependencies::
* Quelpa::
@end menu

@node Prerequisites
@section Prerequisites

Create a client in your wallabag account and note down the @samp{client_id} and @samp{client_secret}.

@uref{https://doc.wallabag.org/img/user/browser_api_management.en.png}

@node Dependencies
@section Dependencies

@itemize
@item
@uref{https://github.com/tkf/emacs-request/tree/master, emacs-request}
@end itemize

@node Quelpa
@section Quelpa

The package @samp{wallabag.el} is not currently available from @uref{https://melpa.org/#/org-ql, MELPA}, but can be installed
directly from github with @uref{https://framagit.org/steckerhalter/quelpa, Quelpa}.

Installing with @uref{https://framagit.org/steckerhalter/quelpa, Quelpa} is easy:

@enumerate
@item
Install @uref{https://framagit.org/steckerhalter/quelpa-use-package#installation, quelpa-use-package} (which can be installed directly from MELPA).
@item
Add this form to your init file:
@end enumerate

@lisp
(use-package wallabag
  :quelpa (wallabag :fetcher github :repo "ifitzpat/wallabag.el")
  :config
  (setq wallabag-client-id "client-id-of-your-registered-app")
  (setq wallabag-client-secret "client-secret-of-your-registered-app")
  (setq wallabag-url "https://your-wallabag.domain")
  (setq wallabag-username "your-username")
  (setq wallabag-password "your-password")
  )
@end lisp

@node Usage
@chapter Usage

@itemize
@item
@end itemize

@menu
* Commands::
@end menu

@node Commands
@section Commands

@itemize
@item
@strong{Add url (at-point) to wallabag:}
@itemize
@item
@samp{wallabag-post-link}
@end itemize
@item
@strong{Add current url in eww to wallabag:}
@itemize
@item
@samp{wallabag-eww-add-url}
@end itemize
@item
@strong{Add elfeed entry at point to wallabag from elfeed-search:}
@itemize
@item
@samp{elfeed-search-wallabag-add}
@end itemize
@item
@strong{Add elfeed entry to wallabag from elfeed-show (when viewing an article):}
@itemize
@item
@samp{elfeed-show-wallabag-add}
@end itemize
@item
@strong{Delete elfeed entry from wallabag from elfeed-show (when viewing an article in a
wallabag RSS feed):}
@itemize
@item
@samp{elfeed-show-wallabag-delete}
@end itemize
@item
@strong{Archive elfeed entry in wallabag from elfeed-show (when viewing an article in a
wallabag RSS feed):}
@itemize
@item
@samp{elfeed-show-wallabag-archive}
@end itemize
@end itemize

@node Changelog
@chapter Changelog

@emph{Note:} Breaking changes may be made before version 1.0, but in the event of major changes, attempts at backward compatibility will be made with obsolescence declarations, translation of arguments, etc.  Users who need stability guarantees before 1.0 may choose to use tagged stable releases.

@menu
* 0.0.2-alpha: 002-alpha. 
* 0.0.1-alpha: 001-alpha. 
@end menu

@node 002-alpha
@section 0.0.2-alpha

@itemize
@item
Inherit elfeed tags when sending a link to wallabag from elfeed
@item
Add/Remove tags in wallabag when you do so in elfeed
@end itemize

@node 001-alpha
@section 0.0.1-alpha

Initial release

@node Notes
@chapter Notes

@menu
* Known issues::
* Credits::
@end menu

@node Known issues
@section Known issues

@node Credits
@section Credits

@itemize
@item
Credit to @uref{https://github.com/protesilaos, prot} for the function to get eww's current url.
@item
Credit to @uref{https://github.com/skeeto, skeeto} for the excellent @uref{https://github.com/skeeto/elfeed, elfeed} RSS reader.
@end itemize

@node License
@chapter License

GPLv3

@bye